# Generated by Django 5.2 on 2025-10-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=90)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=90)),
                ('std_class', models.CharField(max_length=90)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth_table')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=90)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth_table')),
            ],
        ),
    ]
